# Generated by Django 4.2.23 on 2025-07-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cover',
            new_name='cover_image',
        ),
    ]
