# Generated by Django 4.2.23 on 2025-07-26 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
        ('tracking', '0002_timesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('playing', 'Playing'), ('completed', 'Completed')], default='backlog', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
