# Generated by Django 4.2.23 on 2025-07-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_gameuserdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameUserData',
        ),
    ]
